### PR TITLE
wikidata aliases: add philosophical work as work alias

### PR DESCRIPTION
**Pull request by treecrown**

### CODE REVIEW

**Comment by treecrown** [comment]
I wanted to add this Book, but couldn't because of wrong entity type:
https://www.wikidata.org/wiki/Q1170110

**Comment by maxlath** [comment]
thanks! the patch is now online

**Comment by treecrown** [comment]
Thank you very much! This was my first code contribution to a FOSS project. 
By the way, I think inventaire is great and I'm thrilled with your work! Big THANKS for that! ❤️

**Comment by maxlath** [comment]
amazing, welcome to the code side of FOSS! :tada: :grin:

**Pull request merged**
